### ISSUE TITLE
Light theme not consistent

### ISSUE THREAD

**Issue by alxjsn** [flancian/agora-server#22]
If I have the site set to light theme instead of the default dark theme, the dark theme shows up for a split second on each page load (even longer on a page like `/latest`).

Also, certain pages are partially dark theme, which makes the theme inconsistent across the site:
* `/journals`
* `/nodes`
* `/users`

**Comment by flancian** [comment]
Wow Alex, my sincerest apologies for not seeing this earlier! You are among our first bug filers and you ran into a rough edge. I'll be adjusting my inbox, fixing processes.

Thank you for opening this! I haven't been testing light mode as well as I should, obviously :) In essence I suspect the way I did light/dark mode sucks -- and the fact that I don't want to use cookies and keep all state client-only might not help. I need to review ways of better handling themes.

On the inconsistency front: that's definitely easier to fix, on it.

**Comment by alxjsn** [comment]
I ended up making some modifications in my own fork to fix this issue, but I also deviated from this project a bit since my goals are a bit different at times. I really appreciate you starting this project and you're free to to cherry pick commits from my fork if they're useful to you.

Here is one particular commit you may be interested in though: https://github.com/alxjsn/agora-server/commit/1ff0410c5082ad678d1b32755bbdb62804d69e67

**Comment by flancian** [comment]
Oh, that looks interesting indeed :) Thanks for sending along, will cherry
pick that.

Also I see that you've added docker support! I've been meaning to do that
for a while -- I'll probably also pick that if you don't mind.

If you don't mind expanding, I'd love to know what you are doing/planning
to do with this! Let me know if I can help with anything; after some slow
months I'm getting more time to work on this again.
