### ISSUE TITLE
Twitter embed broken redirect

### ISSUE THREAD

**Issue by alxjsn** [flancian/agora-server#26]
When visiting the page `https://anagora.org/@karlicoss/promnesia` I get automatically redirected to a broken Twitter link.

**Comment by flancian** [comment]
Thank you for your bug report! This one is bizarre :) On it.

**Comment by flancian** [comment]
Oh, hmm, do you have auto pull enabled in settings by any chance? I can only reproduce with auto pull currently.

**Comment by flancian** [comment]
It should work now -- I pushed a dirty hack in aaa51e0f0eee43f03d1083b82ed7ebe339376b85 but it at leasts unbreaks a number of pages that had bare html links in auto pull mode, thanks again for the report!

https://anagora.org/@karlicoss/promnesia

I'll leave this open if you don't mind while I think of the proper fix; right now it seems to me fixing this right might require revamping the whole filter system, or alternatively move all button code to the client side.

**Comment by alxjsn** [comment]
Seems to be working for me now. I am pretty sure I had autopull enabled as well.

**Comment by flancian** [comment]
The fix was wrong, pushed 6c7021dcac6c8bc2646662c59462b01eaef30ea0 to unbreak Twitter embeds; it seems this does the trick as I wasn't able to reproduce the bug after I applied this correction, but I need to work on test coverage for the Agora clearly.

**Comment by flancian** [comment]
OK, I think the latest iteration on fixing this is better: it only disables embeds for URLs that are in hrefs, while still adding them in any 'bare' URLs in the same subnode. So I'm calling this good enough and closing. Thanks again for reporting!
