### ISSUE TITLE
Markdown table formatting has stopped working

### ISSUE THREAD

**Issue by ngm** [flancian/agora-server#32]
See e.g. 

https://anagora.org/test-node

![image](https://user-images.githubusercontent.com/172324/148642700-0b8612a2-b8f6-43c5-9372-f79e9933a48c.png)

I think it regressed with addition of footnotes support, I think perhaps this line does not correctly set up `gfm`: https://github.com/flancian/agora-server/commit/70c8175492c94087667b9d351ef866f73d16c429#diff-a085e1e55394a0dc8fc1e75efe631fba60f94661b5483e9d73e8fd05ffba9430R53

**Comment by flancian** [comment]
Oh, thank you for reporting! Looking into this.
