### ISSUE TITLE
HTML entities not rendering correctly

### ISSUE THREAD

**Issue by ngm** [flancian/agora-server#39]
HTML entities using entity numbers don't seem to be rendering correctly as of recently, e.g.

![image](https://user-images.githubusercontent.com/172324/151671671-7aeccacb-01ea-4440-9ed4-5b85198b1620.png)

Related to the change for picking up # as denoting a tag perhaps?

I *think* it used to work OK, though not 100% sure.

**Comment by flancian** [comment]
Thank you for this report! Yes, I'm pretty sure it's faulty code for tag handling that is at fault. Planning to try to fix this today.

**Comment by flancian** [comment]
https://anagora.org/spotify%20is%20going%20to%20ruin%20podcasting now renders well, thank you for contributing to the Agora with your reports!
