### ISSUE TITLE
"Served by the ..." links to localhost:5017 on link.agor.ai

### ISSUE THREAD

**Issue by decentral1se** [flancian/agora-server#76]
"Served by the ..." links to http://localhost:5017

![image](https://github.com/flancian/agora-server/assets/1991377/f5ba15f1-4824-4313-ac57-787983e659e4)

**Comment by flancian** [comment]
Thank you so much for the report!

Yes, I'm using the wrong entrypoint in there container, meant originally
for local development; I'll use this to track fixing this and also exposing
the right name for the Agora while I'm at it (this one I'd supposed to be
the "Agora of the Link").

**Comment by flancian** [comment]
This is now fixed :)

- agora-server now reads agora name and other similar settings from agora.yaml in the root repository if that file exists.
- link.agor.ai now shows 'Agora of the Link' -- and additionally pulls, pushes, etc. work :)
